### ISSUE TITLE
#(publicDir) not working

### ISSUE THREAD

**Issue by sQuarecoW** [vapor-community/wkhtmltopdf#7]
I am trying to use the #(publicDir) you mentioned, but it does not seem te be working: it seems that is simply doesn't get resolved.

I can of course write a leafTag that resolves this, but from the documentation I would think it should just work?

**Comment by bygri** [comment]
Hi there. Yes, I find you are right. It appears that when the package was updated to Vapor 3, it no longer injected the `publicDir` into the template context, but the documentation was not updated. I haven't used Vapor since version 2, so I will amend the documentation.

Alternatively, would you like to contribute something that brings back [this functionality](https://github.com/vapor-community/wkhtmltopdf/commit/454a8a124fed3017bc106b4e069bd9ac2700d323#diff-78094991e32bdd4b9918265dec8b14b8L7)?

**Comment by sQuarecoW** [comment]
Yeah, I'll have a look into it!

**Comment by Kishimotovn** [comment]
Hi, is there any plan to have this working with vapor 4? :-s

**Comment by bygri** [comment]
Hello, not by me, no. PR welcome of course.
